// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package gemara

type Catalog struct {
	Metadata Metadata `json:"metadata,omitempty" yaml:"metadata,omitempty"`

	Title string `json:"title" yaml:"title"`

	ControlFamilies []ControlFamily `json:"control-families,omitempty" yaml:"control-families,omitempty"`

	Threats []Threat `json:"threats,omitempty" yaml:"threats,omitempty"`

	Capabilities []Capability `json:"capabilities,omitempty" yaml:"capabilities,omitempty"`

	ImportedControls []MultiMapping `json:"imported-controls,omitempty" yaml:"imported-controls,omitempty"`

	ImportedThreats []MultiMapping `json:"imported-threats,omitempty" yaml:"imported-threats,omitempty"`

	ImportedCapabilities []MultiMapping `json:"imported-capabilities,omitempty" yaml:"imported-capabilities,omitempty"`
}

// Metadata represents common metadata fields shared across all layers
type Metadata struct {
	Id string `json:"id" yaml:"id"`

	Version string `json:"version,omitempty" yaml:"version,omitempty"`

	Date Date `json:"date,omitempty" yaml:"date,omitempty"`

	Description string `json:"description" yaml:"description"`

	Author Actor `json:"author" yaml:"author"`

	MappingReferences []MappingReference `json:"mapping-references,omitempty" yaml:"mapping-references,omitempty"`

	ApplicabilityCategories []Category `json:"applicability-categories,omitempty" yaml:"applicability-categories,omitempty"`

	Draft bool `json:"draft,omitempty" yaml:"draft,omitempty"`

	Lexicon string `json:"lexicon,omitempty" yaml:"lexicon,omitempty"`
}

// Date represents a date string (ISO 8601 date format)
type Date string

// Actor represents an entity (human or tool) that can perform actions in evaluations.
type Actor struct {
	// Id uniquely identifies the actor.
	Id string `json:"id" yaml:"id"`

	// Name provides the name of the actor.
	Name string `json:"name" yaml:"name"`

	// Type specifies the type of entity interacting in the workflow.
	Type ActorType `json:"type" yaml:"type"`

	// Version specifies the version of the actor (if applicable, e.g., for tools).
	Version string `json:"version,omitempty" yaml:"version,omitempty"`

	// Description provides additional context about the actor.
	Description string `json:"description,omitempty" yaml:"description,omitempty"`

	// Uri provides a general URI for the actor information.
	Uri string `json:"uri,omitempty" yaml:"uri,omitempty"`

	// Contact provides contact information for the actor.
	Contact Contact `json:"contact,omitempty" yaml:"contact,omitempty"`
}

// Contact represents contact information used across multiple layers
type Contact struct {
	// The contact person's name.
	Name string `json:"name" yaml:"name"`

	// The entity with which the contact is affiliated, such as a school or employer.
	Affiliation *string `json:"affiliation,omitempty" yaml:"affiliation,omitempty"`

	// A preferred email address to reach the contact.
	Email *Email `json:"email,omitempty" yaml:"email,omitempty"`

	// A social media handle or profile for the contact.
	Social *string `json:"social,omitempty" yaml:"social,omitempty"`
}

// MappingReference represents a reference to an external document with full metadata.
type MappingReference struct {
	Id string `json:"id" yaml:"id"`

	Title string `json:"title" yaml:"title"`

	Version string `json:"version" yaml:"version"`

	Description string `json:"description,omitempty" yaml:"description,omitempty"`

	Url string `json:"url,omitempty" yaml:"url,omitempty"`
}

// Category represents a category used for applicability or classification
//
// Category represents a logical group of guidelines (i.e. control family)
type Category struct {
	Id string `json:"id" yaml:"id"`

	Title string `json:"title" yaml:"title"`

	Description string `json:"description" yaml:"description"`

	Guidelines []Guideline `json:"guidelines,omitempty" yaml:"guidelines,omitempty"`
}

// Guideline represents a single guideline within a guidance document
type Guideline struct {
	Id string `json:"id" yaml:"id"`

	Title string `json:"title" yaml:"title"`

	Objective string `json:"objective,omitempty" yaml:"objective,omitempty"`

	Recommendations []string `json:"recommendations,omitempty" yaml:"recommendations,omitempty"`

	// Extends allows you to add supplemental guidance within a local guidance document
	// like a control enhancement or from an imported guidance document.
	Extends SingleMapping `json:"extends,omitempty" yaml:"extends,omitempty"`

	Rationale *Rationale `json:"rationale,omitempty" yaml:"rationale,omitempty"`

	Statements []Statement `json:"statements,omitempty" yaml:"statements,omitempty"`

	GuidelineMappings []MultiMapping `json:"guideline-mappings,omitempty" yaml:"guideline-mappings,omitempty"`

	PrincipleMappings []MultiMapping `json:"principle-mappings,omitempty" yaml:"principle-mappings,omitempty"`

	SeeAlso []SingleMapping `json:"see-also,omitempty" yaml:"see-also,omitempty"`
}

// SingleMapping represents how a specific entry (control/requirement/procedure) maps to a MappingReference.
type SingleMapping struct {
	// ReferenceId should reference the corresponding MappingReference id from metadata
	ReferenceId string `json:"reference-id,omitempty" yaml:"reference-id,omitempty"`

	EntryId string `json:"entry-id" yaml:"entry-id"`

	Remarks string `json:"remarks,omitempty" yaml:"remarks,omitempty"`
}

// Rationale provides contextual information to help with development and understanding of
// guideline intent.
type Rationale struct {
	Importance string `json:"importance" yaml:"importance"`

	Goals []string `json:"goals" yaml:"goals"`
}

// Statement represents a sub-statement within a guideline
type Statement struct {
	Id string `json:"id" yaml:"id"`

	Title string `json:"title,omitempty" yaml:"title,omitempty"`

	Text string `json:"text" yaml:"text"`

	Recommendations []string `json:"recommendations,omitempty" yaml:"recommendations,omitempty"`
}

// MultiMapping represents a mapping to an external reference with one or more entries.
type MultiMapping struct {
	// ReferenceId should reference the corresponding MappingReference id from metadata
	ReferenceId string `json:"reference-id" yaml:"reference-id"`

	Entries []MappingEntry `json:"entries" yaml:"entries"`

	Remarks string `json:"remarks,omitempty" yaml:"remarks,omitempty"`
}

// MappingEntry represents a single entry within a mapping
type MappingEntry struct {
	ReferenceId string `json:"reference-id" yaml:"reference-id"`

	Strength int64 `json:"strength" yaml:"strength"`

	Remarks string `json:"remarks,omitempty" yaml:"remarks,omitempty"`
}

type ControlFamily struct {
	Id string `json:"id" yaml:"id"`

	Title string `json:"title" yaml:"title"`

	Description string `json:"description" yaml:"description"`

	Controls []Control `json:"controls" yaml:"controls"`
}

type Control struct {
	Id string `json:"id" yaml:"id"`

	Title string `json:"title" yaml:"title"`

	Objective string `json:"objective" yaml:"objective"`

	AssessmentRequirements []AssessmentRequirement `json:"assessment-requirements" yaml:"assessment-requirements"`

	GuidelineMappings []MultiMapping `json:"guideline-mappings,omitempty" yaml:"guideline-mappings,omitempty"`

	ThreatMappings []MultiMapping `json:"threat-mappings,omitempty" yaml:"threat-mappings,omitempty"`
}

type AssessmentRequirement struct {
	Id string `json:"id" yaml:"id"`

	Text string `json:"text" yaml:"text"`

	Applicability []string `json:"applicability" yaml:"applicability"`

	Recommendation string `json:"recommendation,omitempty" yaml:"recommendation,omitempty"`
}

type Threat struct {
	Id string `json:"id" yaml:"id"`

	Title string `json:"title" yaml:"title"`

	Description string `json:"description" yaml:"description"`

	Capabilities []MultiMapping `json:"capabilities" yaml:"capabilities"`

	ExternalMappings []MultiMapping `json:"external-mappings,omitempty" yaml:"external-mappings,omitempty"`
}

type Capability struct {
	Id string `json:"id" yaml:"id"`

	Title string `json:"title" yaml:"title"`

	Description string `json:"description" yaml:"description"`
}

// Email represents a validated email address pattern
type Email string

// Datetime represents an ISO 8601 formatted datetime string
type Datetime string

// EvaluationLog contains the results of evaluating a set of Layer 2 controls.
type EvaluationLog struct {
	Metadata Metadata `json:"metadata,omitempty" yaml:"metadata,omitempty"`

	Evaluations []*ControlEvaluation `json:"evaluations" yaml:"evaluations"`
}

// ControlEvaluation contains the results of evaluating a single Layer 4 control.
type ControlEvaluation struct {
	Name string `json:"name" yaml:"name"`

	Result Result `json:"result" yaml:"result"`

	Message string `json:"message" yaml:"message"`

	Control SingleMapping `json:"control" yaml:"control"`

	// Enforce that control reference and the assessments' references match
	// This formulation uses the control's reference if the assessment doesn't include a reference
	AssessmentLogs []*AssessmentLog `json:"assessment-logs" yaml:"assessment-logs"`
}

// AssessmentLog contains the results of executing a single assessment procedure for a control requirement.
type AssessmentLog struct {
	// Requirement should map to the assessment requirement for this assessment.
	Requirement SingleMapping `json:"requirement" yaml:"requirement"`

	// Description provides a summary of the assessment procedure.
	Description string `json:"description" yaml:"description"`

	// Result is the overall outcome of the assessment procedure, matching the result of the last step that was run.
	Result Result `json:"result" yaml:"result"`

	// Message provides additional context about the assessment result.
	Message string `json:"message" yaml:"message"`

	// Applicability is elevated from the Layer 2 Assessment Requirement to aid in execution and reporting.
	Applicability []string `json:"applicability" yaml:"applicability"`

	// Steps are sequential actions taken as part of the assessment, which may halt the assessment if a failure occurs.
	Steps []AssessmentStep `json:"steps" yaml:"steps"`

	// Steps-executed is the number of steps that were executed as part of the assessment.
	StepsExecuted int64 `json:"steps-executed,omitempty" yaml:"steps-executed,omitempty"`

	// Start is the timestamp when the assessment began.
	Start Datetime `json:"start" yaml:"start"`

	// End is the timestamp when the assessment concluded.
	End Datetime `json:"end,omitempty" yaml:"end,omitempty"`

	// Recommendation provides guidance on how to address a failed assessment.
	Recommendation string `json:"recommendation,omitempty" yaml:"recommendation,omitempty"`
}

type Guidance struct {
	Metadata Metadata `json:"metadata,omitempty" yaml:"metadata,omitempty"`

	Title string `json:"title" yaml:"title"`

	DocumentType DocumentType `json:"document-type" yaml:"document-type"`

	Exemptions []Exemption `json:"exemptions,omitempty" yaml:"exemptions,omitempty"`

	// Introductory text for the document to be used during rendering
	FrontMatter string `json:"front-matter,omitempty" yaml:"front-matter,omitempty"`

	Categories []Category `json:"categories,omitempty" yaml:"categories,omitempty"`
}

type DocumentType string

// Exemption represents an exemption with a reason and optional redirect
type Exemption struct {
	Reason string `json:"reason" yaml:"reason"`

	Redirect MultiMapping `json:"redirect,omitempty" yaml:"redirect,omitempty"`
}

// Core Document Structure
type Policy struct {
	Metadata Metadata `json:"metadata" yaml:"metadata"`

	OrganizationID string `json:"organization-id" yaml:"organization-id"`

	Title string `json:"title" yaml:"title"`

	Purpose string `json:"purpose" yaml:"purpose"`

	Contacts Contacts `json:"contacts" yaml:"contacts"`

	Scope Scope `json:"scope" yaml:"scope"`

	// ImportedPolicies: References to other Layer 3 Policy documents for policy composition.
	// When a policy imports another policy via ImportedPolicies:
	//   - ImplementationPlan: Inherited, evaluators are ADDITIVE (union) if child also defines evaluators
	//
	// - Merged reference sets (can be modified):
	//   - ControlReferences: Merged from imported policy, can be modified via ControlModifications
	//   - GuidanceReferences: Merged from imported policy, can be modified via GuidelineModifications
	//
	// - Modifications chain sequentially (e.g., Base → Parent → Child), preserving all modifications
	ImportedPolicies []PolicyMapping `json:"imported-policies,omitempty" yaml:"imported-policies,omitempty"`

	ImplementationPlan ImplementationPlan `json:"implementation-plan,omitempty" yaml:"implementation-plan,omitempty"`

	// GuidanceReferences: References to Layer 1 Guidance documents (abstract, high-level guidance).
	// Modifications chain sequentially (e.g., Guidance → Parent → Child), preserving all modifications.
	GuidanceReferences []PolicyMapping `json:"guidance-references,omitempty" yaml:"guidance-references,omitempty"`

	// ControlReferences: References to Layer 2 Control catalogs (technology-specific, threat-informed controls).
	// Modifications chain sequentially (e.g., Catalog → Parent → Child), preserving all modifications.
	ControlReferences []PolicyMapping `json:"control-references,omitempty" yaml:"control-references,omitempty"`
}

type Contacts struct {
	Responsible []Contact `json:"responsible" yaml:"responsible"`

	Accountable []Contact `json:"accountable" yaml:"accountable"`

	Consulted []Contact `json:"consulted,omitempty" yaml:"consulted,omitempty"`

	Informed []Contact `json:"informed,omitempty" yaml:"informed,omitempty"`
}

// Scope is descriptive metadata for tools.
// When importing policies: Inherited from imported policy, but child's scope OVERRIDES parent's if defined.
type Scope struct {
	// geopolitical boundaries such as region names or jurisdictions
	Boundaries []string `json:"boundaries,omitempty" yaml:"boundaries,omitempty"`

	// names of technology categories or services
	Technologies []string `json:"technologies,omitempty" yaml:"technologies,omitempty"`

	// names of organizations who make the listed technologies available
	Providers []string `json:"providers,omitempty" yaml:"providers,omitempty"`
}

// Layer 3 specific mapping that extends common Mapping with modifications.
// Used by ImportedPolicies, GuidanceReferences, and ControlReferences.
// Modifications chain sequentially when importing policies (e.g., Base → Parent → Child), preserving all modifications.
type PolicyMapping struct {
	ReferenceId string `json:"reference-id" yaml:"reference-id"`

	// ControlModifications: Modify controls from referenced catalog/policy.
	// When used in ImportedPolicies: Modifies controls from imported policy's ControlReferences (sequential chain).
	// When used in ControlReferences: Modifies controls from referenced catalog (sequential chain).
	ControlModifications []ControlModifier `json:"control-modifications,omitempty" yaml:"control-modifications,omitempty"`

	// AssessmentRequirementModifications: Modify assessment requirements (which have evaluators).
	// When used in ImportedPolicies: Modifies assessment requirements from imported policy's ControlReferences (sequential chain).
	// When used in ControlReferences: Modifies assessment requirements from referenced catalog (sequential chain).
	AssessmentRequirementModifications []AssessmentRequirementModifier `json:"assessment-requirement-modifications,omitempty" yaml:"assessment-requirement-modifications,omitempty"`

	// GuidelineModifications: Modify guidelines from referenced guidance document.
	// When used in ImportedPolicies: Modifies guidelines from imported policy's GuidanceReferences (sequential chain).
	// When used in GuidanceReferences: Modifies guidelines from referenced guidance document (sequential chain).
	GuidelineModifications []GuidelineModifier `json:"guideline-modifications,omitempty" yaml:"guideline-modifications,omitempty"`

	// StatementModifications: Modify statements within guidelines.
	// When used in ImportedPolicies: Modifies statements from imported policy's GuidanceReferences (sequential chain).
	// When used in GuidanceReferences: Modifies statements from referenced guidance document (sequential chain).
	StatementModifications []StatementModifier `json:"statement-modifications,omitempty" yaml:"statement-modifications,omitempty"`
}

// Modifier Types
type ControlModifier struct {
	Id string `json:"id,omitempty" yaml:"id,omitempty"`

	TargetId string `json:"target-id" yaml:"target-id"`

	ModType ModType `json:"modification-type" yaml:"modification-type"`

	ModificationRationale string `json:"modification-rationale" yaml:"modification-rationale"`

	Overrides *Control `json:"overrides,omitempty" yaml:"overrides,omitempty"`

	Extensions *ControlExtensions `json:"extensions,omitempty" yaml:"extensions,omitempty"`
}

// ModType: Semantic modification types for policy tailoring.
type ModType string

type ControlExtensions struct {
	Severity Severity `json:"severity,omitempty" yaml:"severity,omitempty"`

	AutoRemediationAllowed bool `json:"auto-remediation-allowed,omitempty" yaml:"auto-remediation-allowed,omitempty"`

	DeploymentGateAllowed bool `json:"deployment-gate-allowed,omitempty" yaml:"deployment-gate-allowed,omitempty"`
}

type AssessmentRequirementModifier struct {
	Id string `json:"id,omitempty" yaml:"id,omitempty"`

	TargetId string `json:"target-id" yaml:"target-id"`

	ModType ModType `json:"modification-type" yaml:"modification-type"`

	ModificationRationale string `json:"modification-rationale" yaml:"modification-rationale"`

	Overrides *AssessmentRequirement `json:"overrides,omitempty" yaml:"overrides,omitempty"`

	Extensions *AssessmentRequirementExtensions `json:"extensions,omitempty" yaml:"extensions,omitempty"`
}

type AssessmentRequirementExtensions struct {
	RequiredEvaluators []string `json:"required-evaluators,omitempty" yaml:"required-evaluators,omitempty"`

	OptionalEvaluators []string `json:"optional-evaluators,omitempty" yaml:"optional-evaluators,omitempty"`

	EvidenceRequirements string `json:"evidence-requirements,omitempty" yaml:"evidence-requirements,omitempty"`

	ResolutionStrategy ResolutionStrategy `json:"resolution-strategy,omitempty" yaml:"resolution-strategy,omitempty"`

	EvaluationPoints []EvaluationPoint `json:"evaluation-points,omitempty" yaml:"evaluation-points,omitempty"`
}

type EvaluationPoint string

type GuidelineModifier struct {
	Id string `json:"id,omitempty" yaml:"id,omitempty"`

	TargetId string `json:"target-id" yaml:"target-id"`

	ModType ModType `json:"modification-type" yaml:"modification-type"`

	ModificationRationale string `json:"modification-rationale" yaml:"modification-rationale"`

	Overrides *Guideline `json:"overrides,omitempty" yaml:"overrides,omitempty"`
}

type StatementModifier struct {
	Id string `json:"id,omitempty" yaml:"id,omitempty"`

	TargetId string `json:"target-id" yaml:"target-id"`

	ModType ModType `json:"modification-type" yaml:"modification-type"`

	ModificationRationale string `json:"modification-rationale" yaml:"modification-rationale"`

	Overrides *Statement `json:"overrides,omitempty" yaml:"overrides,omitempty"`
}

type ImplementationPlan struct {
	// The process through which notified parties should be made aware of this policy
	NotificationProcess string `json:"notification-process,omitempty" yaml:"notification-process,omitempty"`

	NotifiedParties []NotificationGroup `json:"notified-parties,omitempty" yaml:"notified-parties,omitempty"`

	EvaluationTimeline ImplementationDetails `json:"evaluation-timeline" yaml:"evaluation-timeline"`

	// Evaluators: Actors (human or software) that perform assessments.
	// When importing policies: Inherited from imported policy, evaluators are ADDITIVE (union) if child also defines evaluators.
	// This prevents broken evaluator references in assessment requirements.
	Evaluators []Actor `json:"evaluators,omitempty" yaml:"evaluators,omitempty"`

	EnforcementTimeline ImplementationDetails `json:"enforcement-timeline" yaml:"enforcement-timeline"`

	EnforcementMethods []EnforcementMethod `json:"enforcement-methods,omitempty" yaml:"enforcement-methods,omitempty"`

	// The consequence that will be applied in the event that noncompliance is detected
	NoncomplianceConsequence string `json:"noncompliance-consequence,omitempty" yaml:"noncompliance-consequence,omitempty"`
}

type NotificationGroup string

type ImplementationDetails struct {
	Start Datetime `json:"start" yaml:"start"`

	End Datetime `json:"end,omitempty" yaml:"end,omitempty"`

	Notes string `json:"notes,omitempty" yaml:"notes,omitempty"`
}

type EnforcementMethod string
