// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package gemara

type Catalog struct {
	Metadata Metadata `json:"metadata,omitempty" yaml:"metadata,omitempty"`

	Title string `json:"title" yaml:"title"`

	ControlFamilies []ControlFamily `json:"control-families,omitempty" yaml:"control-families,omitempty"`

	Threats []Threat `json:"threats,omitempty" yaml:"threats,omitempty"`

	Capabilities []Capability `json:"capabilities,omitempty" yaml:"capabilities,omitempty"`

	ImportedControls []MultiMapping `json:"imported-controls,omitempty" yaml:"imported-controls,omitempty"`

	ImportedThreats []MultiMapping `json:"imported-threats,omitempty" yaml:"imported-threats,omitempty"`

	ImportedCapabilities []MultiMapping `json:"imported-capabilities,omitempty" yaml:"imported-capabilities,omitempty"`
}

// Metadata represents common metadata fields shared across all layers
type Metadata struct {
	Id string `json:"id" yaml:"id"`

	Version string `json:"version,omitempty" yaml:"version,omitempty"`

	Date Date `json:"date,omitempty" yaml:"date,omitempty"`

	Description string `json:"description" yaml:"description"`

	Author Actor `json:"author" yaml:"author"`

	MappingReferences []MappingReference `json:"mapping-references,omitempty" yaml:"mapping-references,omitempty"`

	ApplicabilityCategories []Category `json:"applicability-categories,omitempty" yaml:"applicability-categories,omitempty"`

	Draft bool `json:"draft,omitempty" yaml:"draft,omitempty"`

	Lexicon string `json:"lexicon,omitempty" yaml:"lexicon,omitempty"`
}

// Date represents a date string (ISO 8601 date format)
type Date string

// Actor represents an entity (human or tool) that can perform actions in evaluations.
type Actor struct {
	// Id uniquely identifies the actor.
	Id string `json:"id" yaml:"id"`

	// Name provides the name of the actor.
	Name string `json:"name" yaml:"name"`

	// Type specifies the type of entity interacting in the workflow.
	Type ActorType `json:"type" yaml:"type"`

	// Version specifies the version of the actor (if applicable, e.g., for tools).
	Version string `json:"version,omitempty" yaml:"version,omitempty"`

	// Description provides additional context about the actor.
	Description string `json:"description,omitempty" yaml:"description,omitempty"`

	// Uri provides a general URI for the actor information.
	Uri string `json:"uri,omitempty" yaml:"uri,omitempty"`

	// Contact provides contact information for the actor.
	Contact Contact `json:"contact,omitempty" yaml:"contact,omitempty"`
}

// Contact represents contact information used across multiple layers
type Contact struct {
	// The contact person's name.
	Name string `json:"name" yaml:"name"`

	// The entity with which the contact is affiliated, such as a school or employer.
	Affiliation *string `json:"affiliation,omitempty" yaml:"affiliation,omitempty"`

	// A preferred email address to reach the contact.
	Email *Email `json:"email,omitempty" yaml:"email,omitempty"`

	// A social media handle or profile for the contact.
	Social *string `json:"social,omitempty" yaml:"social,omitempty"`
}

// MappingReference represents a reference to an external document with full metadata.
type MappingReference struct {
	Id string `json:"id" yaml:"id"`

	Title string `json:"title" yaml:"title"`

	Version string `json:"version" yaml:"version"`

	Description string `json:"description,omitempty" yaml:"description,omitempty"`

	Url string `json:"url,omitempty" yaml:"url,omitempty"`
}

// Category represents a category used for applicability or classification
//
// Category represents a logical group of guidelines (i.e. control family)
type Category struct {
	Id string `json:"id" yaml:"id"`

	Title string `json:"title" yaml:"title"`

	Description string `json:"description" yaml:"description"`

	Guidelines []Guideline `json:"guidelines,omitempty" yaml:"guidelines,omitempty"`
}

type Guideline struct {
	Id string `json:"id" yaml:"id"`

	Title string `json:"title" yaml:"title"`

	Objective string `json:"objective,omitempty" yaml:"objective,omitempty"`

	// Maps to fields commonly seen in controls with implementation guidance
	Recommendations []string `json:"recommendations,omitempty" yaml:"recommendations,omitempty"`

	// For control enhancements (ex. AC-2(1) in 800-53)
	// The base-guideline-id is needed to achieve full context for the enhancement
	BaseGuidelineID string `json:"base-guideline-id,omitempty" yaml:"base-guideline-id,omitempty"`

	Rationale *Rationale `json:"rationale,omitempty" yaml:"rationale,omitempty"`

	// Represents individual guideline parts/statements
	GuidelineParts []Part `json:"guideline-parts,omitempty" yaml:"guideline-parts,omitempty"`

	// Crosswalking this guideline to other guidelines in other documents
	GuidelineMappings []MultiMapping `json:"guideline-mappings,omitempty" yaml:"guideline-mappings,omitempty"`

	// A list for associated key principle ids
	PrincipleMappings []MultiMapping `json:"principle-mappings,omitempty" yaml:"principle-mappings,omitempty"`

	// This is akin to related controls, but using more explicit terminology
	SeeAlso []string `json:"see-also,omitempty" yaml:"see-also,omitempty"`
}

// Rationale provides contextual information to help with development and understanding of
// guideline intent.
type Rationale struct {
	// Negative results expected from the guideline's lack of implementation
	Risks []Risk `json:"risks" yaml:"risks"`

	// Positive results expected from the guideline's implementation
	Outcomes []Outcome `json:"outcomes" yaml:"outcomes"`
}

type Risk struct {
	Title string `json:"title" yaml:"title"`

	Description string `json:"description" yaml:"description"`
}

type Outcome struct {
	Title string `json:"title" yaml:"title"`

	Description string `json:"description" yaml:"description"`
}

// Parts include sub-statements of a guideline that can be assessed individually
type Part struct {
	Id string `json:"id" yaml:"id"`

	Title string `json:"title,omitempty" yaml:"title,omitempty"`

	Text string `json:"text" yaml:"text"`

	Recommendations []string `json:"recommendations,omitempty" yaml:"recommendations,omitempty"`
}

// MultiMapping represents a mapping to an external reference with one or more entries.
type MultiMapping struct {
	// ReferenceId should reference the corresponding MappingReference id from metadata
	ReferenceId string `json:"reference-id" yaml:"reference-id"`

	Entries []MappingEntry `json:"entries" yaml:"entries"`

	Remarks string `json:"remarks,omitempty" yaml:"remarks,omitempty"`
}

// MappingEntry represents a single entry within a mapping
type MappingEntry struct {
	ReferenceId string `json:"reference-id" yaml:"reference-id"`

	Strength int64 `json:"strength" yaml:"strength"`

	Remarks string `json:"remarks,omitempty" yaml:"remarks,omitempty"`
}

type ControlFamily struct {
	Id string `json:"id" yaml:"id"`

	Title string `json:"title" yaml:"title"`

	Description string `json:"description" yaml:"description"`

	Controls []Control `json:"controls" yaml:"controls"`
}

type Control struct {
	Id string `json:"id" yaml:"id"`

	Title string `json:"title" yaml:"title"`

	Objective string `json:"objective" yaml:"objective"`

	AssessmentRequirements []AssessmentRequirement `json:"assessment-requirements" yaml:"assessment-requirements"`

	GuidelineMappings []MultiMapping `json:"guideline-mappings,omitempty" yaml:"guideline-mappings,omitempty"`

	ThreatMappings []MultiMapping `json:"threat-mappings,omitempty" yaml:"threat-mappings,omitempty"`
}

type AssessmentRequirement struct {
	Id string `json:"id" yaml:"id"`

	Text string `json:"text" yaml:"text"`

	Applicability []string `json:"applicability" yaml:"applicability"`

	Recommendation string `json:"recommendation,omitempty" yaml:"recommendation,omitempty"`
}

type Threat struct {
	Id string `json:"id" yaml:"id"`

	Title string `json:"title" yaml:"title"`

	Description string `json:"description" yaml:"description"`

	Capabilities []MultiMapping `json:"capabilities" yaml:"capabilities"`

	ExternalMappings []MultiMapping `json:"external-mappings,omitempty" yaml:"external-mappings,omitempty"`
}

type Capability struct {
	Id string `json:"id" yaml:"id"`

	Title string `json:"title" yaml:"title"`

	Description string `json:"description" yaml:"description"`
}

// Email represents a validated email address pattern
type Email string

// Datetime represents an ISO 8601 formatted datetime string
type Datetime string

// EvaluationPlan defines how a set of Layer 2 controls are to be evaluated.
type EvaluationPlan struct {
	Metadata Metadata `json:"metadata,omitempty" yaml:"metadata,omitempty"`

	Plans []AssessmentPlan `json:"plans" yaml:"plans"`
}

// AssessmentPlan defines all testing procedures for a control id.
type AssessmentPlan struct {
	// Control points to the Layer 2 control being evaluated.
	Control SingleMapping `json:"control" yaml:"control"`

	// Assessments defines possible testing procedures to evaluate the control.
	//
	// Enforce that control reference and the assessments' references match
	// This formulation uses the control's reference if the assessment doesn't include a reference
	Assessments []Assessment `json:"assessments" yaml:"assessments"`
}

// SingleMapping represents how a specific entry (control/requirement/procedure) maps to a MappingReference.
type SingleMapping struct {
	// ReferenceId should reference the corresponding MappingReference id from metadata
	ReferenceId string `json:"reference-id,omitempty" yaml:"reference-id,omitempty"`

	EntryId string `json:"entry-id" yaml:"entry-id"`

	Remarks string `json:"remarks,omitempty" yaml:"remarks,omitempty"`
}

// EvaluationLog contains the results of evaluating a set of Layer 2 controls.
type EvaluationLog struct {
	Evaluations []*ControlEvaluation `json:"evaluations" yaml:"evaluations"`

	Metadata Metadata `json:"metadata,omitempty" yaml:"metadata,omitempty"`
}

// ControlEvaluation contains the results of evaluating a single Layer 4 control.
type ControlEvaluation struct {
	Name string `json:"name" yaml:"name"`

	Result Result `json:"result" yaml:"result"`

	Message string `json:"message" yaml:"message"`

	Control SingleMapping `json:"control" yaml:"control"`

	// Enforce that control reference and the assessments' references match
	// This formulation uses the control's reference if the assessment doesn't include a reference
	AssessmentLogs []*AssessmentLog `json:"assessment-logs" yaml:"assessment-logs"`
}

// AssessmentLog contains the results of executing a single assessment procedure for a control requirement.
type AssessmentLog struct {
	// Requirement should map to the assessment requirement for this assessment.
	Requirement SingleMapping `json:"requirement" yaml:"requirement"`

	// Procedure should map to the assessment procedure being executed.
	Procedure SingleMapping `json:"procedure" yaml:"procedure"`

	// Description provides a summary of the assessment procedure.
	Description string `json:"description" yaml:"description"`

	// Result is the overall outcome of the assessment procedure, matching the result of the last step that was run.
	Result Result `json:"result" yaml:"result"`

	// Message provides additional context about the assessment result.
	Message string `json:"message" yaml:"message"`

	// Applicability is elevated from the Layer 2 Assessment Requirement to aid in execution and reporting.
	Applicability []string `json:"applicability" yaml:"applicability"`

	// Steps are sequential actions taken as part of the assessment, which may halt the assessment if a failure occurs.
	Steps []AssessmentStep `json:"steps" yaml:"steps"`

	// Steps-executed is the number of steps that were executed as part of the assessment.
	StepsExecuted int64 `json:"steps-executed,omitempty" yaml:"steps-executed,omitempty"`

	// Start is the timestamp when the assessment began.
	Start Datetime `json:"start" yaml:"start"`

	// End is the timestamp when the assessment concluded.
	End Datetime `json:"end,omitempty" yaml:"end,omitempty"`

	// Recommendation provides guidance on how to address a failed assessment.
	Recommendation string `json:"recommendation,omitempty" yaml:"recommendation,omitempty"`
}

type GuidanceDocument struct {
	Metadata Metadata `json:"metadata,omitempty" yaml:"metadata,omitempty"`

	Title string `json:"title" yaml:"title"`

	DocumentType DocumentType `json:"document-type" yaml:"document-type"`

	Exemptions []Exemption `json:"exemptions,omitempty" yaml:"exemptions,omitempty"`

	// Introductory text for the document to be used during rendering
	FrontMatter string `json:"front-matter,omitempty" yaml:"front-matter,omitempty"`

	Categories []Category `json:"categories,omitempty" yaml:"categories,omitempty"`

	// For inheriting from other guidance documents to create tailored documents/baselines
	ImportedGuidelines []MultiMapping `json:"imported-guidelines,omitempty" yaml:"imported-guidelines,omitempty"`

	ImportedPrinciples []MultiMapping `json:"imported-principles,omitempty" yaml:"imported-principles,omitempty"`
}

type DocumentType string

// Exemption represents an exemption with a reason and optional redirect
type Exemption struct {
	Reason string `json:"reason" yaml:"reason"`

	Redirect MultiMapping `json:"redirect,omitempty" yaml:"redirect,omitempty"`
}

// Core Document Structure
type PolicyDocument struct {
	Metadata Metadata `json:"metadata" yaml:"metadata"`

	OrganizationID string `json:"organization-id" yaml:"organization-id"`

	Title string `json:"title" yaml:"title"`

	Purpose string `json:"purpose" yaml:"purpose"`

	Contacts Contacts `json:"contacts" yaml:"contacts"`

	Scope Scope `json:"scope" yaml:"scope"`

	ImplementationPlan ImplementationPlan `json:"implementation-plan,omitempty" yaml:"implementation-plan,omitempty"`

	GuidanceReferences []PolicyMapping `json:"guidance-references" yaml:"guidance-references"`

	ControlReferences []PolicyMapping `json:"control-references" yaml:"control-references"`
}

type Contacts struct {
	Responsible []Contact `json:"responsible" yaml:"responsible"`

	Accountable []Contact `json:"accountable" yaml:"accountable"`

	Consulted []Contact `json:"consulted,omitempty" yaml:"consulted,omitempty"`

	Informed []Contact `json:"informed,omitempty" yaml:"informed,omitempty"`
}

type Scope struct {
	// geopolitical boundaries such as region names or jurisdictions
	Boundaries []string `json:"boundaries,omitempty" yaml:"boundaries,omitempty"`

	// names of technology categories or services
	Technologies []string `json:"technologies,omitempty" yaml:"technologies,omitempty"`

	// names of organizations who make the listed technologies available
	Providers []string `json:"providers,omitempty" yaml:"providers,omitempty"`
}

type ImplementationPlan struct {
	// The process through which notified parties should be made aware of this policy
	NotificationProcess string `json:"notification-process,omitempty" yaml:"notification-process,omitempty"`

	NotifiedParties []NotificationGroup `json:"notified-parties,omitempty" yaml:"notified-parties,omitempty"`

	Evaluation ImplementationDetails `json:"evaluation" yaml:"evaluation"`

	EvaluationPoints []EvaluationPoint `json:"evaluation-points,omitempty" yaml:"evaluation-points,omitempty"`

	Enforcement ImplementationDetails `json:"enforcement" yaml:"enforcement"`

	EnforcementMethods []EnforcementMethod `json:"enforcement-methods,omitempty" yaml:"enforcement-methods,omitempty"`

	// The process that will be followed in the event that noncompliance is detected in an applicable resource
	NoncompliancePlan string `json:"noncompliance-plan,omitempty" yaml:"noncompliance-plan,omitempty"`
}

type NotificationGroup string

type ImplementationDetails struct {
	Start Datetime `json:"start" yaml:"start"`

	End Datetime `json:"end,omitempty" yaml:"end,omitempty"`

	Notes string `json:"notes" yaml:"notes"`
}

type EvaluationPoint string

type EnforcementMethod string

type PolicyMapping struct {
	ReferenceId string `json:"reference-id" yaml:"reference-id"`

	InScope Scope `json:"in-scope" yaml:"in-scope"`

	OutOfScope Scope `json:"out-of-scope" yaml:"out-of-scope"`

	ControlModifications []ControlModifier `json:"control-modifications" yaml:"control-modifications"`

	AssessmentRequirementModifications []AssessmentRequirementModifier `json:"assessment-requirement-modifications" yaml:"assessment-requirement-modifications"`

	GuidelineModifications []GuidelineModifier `json:"guideline-modifications" yaml:"guideline-modifications"`
}

// Modifier Types
type ControlModifier struct {
	TargetId string `json:"target-id" yaml:"target-id"`

	ModType ModType `json:"modification-type" yaml:"modification-type"`

	ModificationRationale string `json:"modification-rationale" yaml:"modification-rationale"`

	Title string `json:"title,omitempty" yaml:"title,omitempty"`

	Objective string `json:"objective,omitempty" yaml:"objective,omitempty"`
}

type ModType string

type AssessmentRequirementModifier struct {
	TargetId string `json:"target-id" yaml:"target-id"`

	ModType ModType `json:"modification-type" yaml:"modification-type"`

	ModificationRationale string `json:"modification-rationale" yaml:"modification-rationale"`

	Text string `json:"text" yaml:"text"`

	Applicability []string `json:"applicability" yaml:"applicability"`

	Recommendation string `json:"recommendation,omitempty" yaml:"recommendation,omitempty"`
}

type GuidelineModifier struct {
	TargetId string `json:"target-id" yaml:"target-id"`

	ModType ModType `json:"modification-type" yaml:"modification-type"`

	ModificationRationale string `json:"modification-rationale" yaml:"modification-rationale"`

	Title string `json:"title" yaml:"title"`

	Objective string `json:"objective,omitempty" yaml:"objective,omitempty"`

	Recommendations []string `json:"recommendations,omitempty" yaml:"recommendations,omitempty"`

	BaseGuidelineID string `json:"base-guideline-id,omitempty" yaml:"base-guideline-id,omitempty"`

	Rationale *string `json:"rationale,omitempty" yaml:"rationale,omitempty"`

	GuidelineMappings []MultiMapping `json:"guideline-mappings,omitempty" yaml:"guideline-mappings,omitempty"`

	PrincipleMappings []MultiMapping `json:"principle-mappings,omitempty" yaml:"principle-mappings,omitempty"`

	SeeAlso []string `json:"see-also,omitempty" yaml:"see-also,omitempty"`

	ExternalReferences []string `json:"external-references,omitempty" yaml:"external-references,omitempty"`
}

// Assessment defines all testing procedures for a requirement.
type Assessment struct {
	// RequirementId points to the requirement being tested.
	Requirement SingleMapping `json:"requirement" yaml:"requirement"`

	// Procedures defines possible testing procedures to evaluate the requirement.
	Procedures []AssessmentProcedure `json:"procedures" yaml:"procedures"`
}

// AssessmentProcedure describes a testing procedure for evaluating a Layer 2 control requirement.
type AssessmentProcedure struct {
	// Id uniquely identifies the assessment procedure being executed
	Id string `json:"id" yaml:"id"`

	// Name provides a summary of the procedure
	Name string `json:"name" yaml:"name"`

	// Description provides a detailed explanation of the procedure
	Description string `json:"description" yaml:"description"`

	// Documentation provides a URL to documentation that describes how the assessment procedure evaluates the control requirement
	Documentation string `json:"documentation,omitempty" yaml:"documentation,omitempty"`
}

type PartModifier struct {
	TargetId string `json:"target-id" yaml:"target-id"`

	ModType ModType `json:"modification-type" yaml:"modification-type"`

	ModificationRationale string `json:"modification-rationale" yaml:"modification-rationale"`

	Title string `json:"title,omitempty" yaml:"title,omitempty"`

	Prose string `json:"prose" yaml:"prose"`

	Recommendations []string `json:"recommendations,omitempty" yaml:"recommendations,omitempty"`
}
