// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package gemara

type Catalog struct {
	Metadata Metadata `json:"metadata,omitempty" yaml:"metadata,omitempty"`

	Title string `json:"title" yaml:"title"`

	Families []Family `json:"families,omitempty" yaml:"families,omitempty"`

	Controls []Control `json:"controls,omitempty" yaml:"controls,omitempty"`

	Threats []Threat `json:"threats,omitempty" yaml:"threats,omitempty"`

	Capabilities []Capability `json:"capabilities,omitempty" yaml:"capabilities,omitempty"`

	ImportedControls []MultiMapping `json:"imported-controls,omitempty" yaml:"imported-controls,omitempty"`

	ImportedThreats []MultiMapping `json:"imported-threats,omitempty" yaml:"imported-threats,omitempty"`

	ImportedCapabilities []MultiMapping `json:"imported-capabilities,omitempty" yaml:"imported-capabilities,omitempty"`
}

// Metadata represents common metadata fields shared across all layers
type Metadata struct {
	Id string `json:"id" yaml:"id"`

	Version string `json:"version,omitempty" yaml:"version,omitempty"`

	Date Date `json:"date,omitempty" yaml:"date,omitempty"`

	Description string `json:"description" yaml:"description"`

	Author Actor `json:"author" yaml:"author"`

	MappingReferences []MappingReference `json:"mapping-references,omitempty" yaml:"mapping-references,omitempty"`

	ApplicabilityCategories []Category `json:"applicability-categories,omitempty" yaml:"applicability-categories,omitempty"`

	Draft bool `json:"draft,omitempty" yaml:"draft,omitempty"`

	Lexicon string `json:"lexicon,omitempty" yaml:"lexicon,omitempty"`
}

// Date represents a date string (ISO 8601 date format)
type Date string

// Actor represents an entity (human or tool) that can perform actions in evaluations.
type Actor struct {
	// Id uniquely identifies the actor.
	Id string `json:"id" yaml:"id"`

	// Name provides the name of the actor.
	Name string `json:"name" yaml:"name"`

	// Type specifies the type of entity interacting in the workflow.
	Type ActorType `json:"type" yaml:"type"`

	// Version specifies the version of the actor (if applicable, e.g., for tools).
	Version string `json:"version,omitempty" yaml:"version,omitempty"`

	// Description provides additional context about the actor.
	Description string `json:"description,omitempty" yaml:"description,omitempty"`

	// Uri provides a general URI for the actor information.
	Uri string `json:"uri,omitempty" yaml:"uri,omitempty"`

	// Contact provides contact information for the actor.
	Contact Contact `json:"contact,omitempty" yaml:"contact,omitempty"`
}

// Contact represents contact information used across multiple layers
type Contact struct {
	// The contact person's name.
	Name string `json:"name" yaml:"name"`

	// The entity with which the contact is affiliated, such as a school or employer.
	Affiliation *string `json:"affiliation,omitempty" yaml:"affiliation,omitempty"`

	// A preferred email address to reach the contact.
	Email *Email `json:"email,omitempty" yaml:"email,omitempty"`

	// A social media handle or profile for the contact.
	Social *string `json:"social,omitempty" yaml:"social,omitempty"`
}

// MappingReference represents a reference to an external document with full metadata.
type MappingReference struct {
	Id string `json:"id" yaml:"id"`

	Title string `json:"title" yaml:"title"`

	Version string `json:"version" yaml:"version"`

	Description string `json:"description,omitempty" yaml:"description,omitempty"`

	Url string `json:"url,omitempty" yaml:"url,omitempty"`
}

// Category represents a category used for applicability or classification
type Category struct {
	Id string `json:"id" yaml:"id"`

	Title string `json:"title" yaml:"title"`

	Description string `json:"description" yaml:"description"`
}

// Family represents a logical grouping of guidelines or controls which share a common purpose or function
type Family struct {
	Id string `json:"id" yaml:"id"`

	Title string `json:"title" yaml:"title"`

	Description string `json:"description" yaml:"description"`
}

type Control struct {
	Id string `json:"id" yaml:"id"`

	Title string `json:"title" yaml:"title"`

	Objective string `json:"objective" yaml:"objective"`

	// Family id that this control belongs to
	Family string `json:"family" yaml:"family"`

	AssessmentRequirements []AssessmentRequirement `json:"assessment-requirements" yaml:"assessment-requirements"`

	GuidelineMappings []MultiMapping `json:"guideline-mappings,omitempty" yaml:"guideline-mappings,omitempty"`

	ThreatMappings []MultiMapping `json:"threat-mappings,omitempty" yaml:"threat-mappings,omitempty"`
}

type AssessmentRequirement struct {
	Id string `json:"id" yaml:"id"`

	Text string `json:"text" yaml:"text"`

	Applicability []string `json:"applicability" yaml:"applicability"`

	Recommendation string `json:"recommendation,omitempty" yaml:"recommendation,omitempty"`
}

// MultiMapping represents a mapping to an external reference with one or more entries.
type MultiMapping struct {
	// ReferenceId should reference the corresponding MappingReference id from metadata
	ReferenceId string `json:"reference-id" yaml:"reference-id"`

	Entries []MappingEntry `json:"entries" yaml:"entries"`

	Remarks string `json:"remarks,omitempty" yaml:"remarks,omitempty"`
}

// MappingEntry represents a single entry within a mapping
type MappingEntry struct {
	ReferenceId string `json:"reference-id" yaml:"reference-id"`

	// Strength quantifies the degree of correlation or relationship between the mapped items.
	// Range: 1-10. Zero value means not yet quantified.
	Strength int64 `json:"strength,omitempty" yaml:"strength,omitempty"`

	Remarks string `json:"remarks,omitempty" yaml:"remarks,omitempty"`
}

type Threat struct {
	Id string `json:"id" yaml:"id"`

	Title string `json:"title" yaml:"title"`

	Description string `json:"description" yaml:"description"`

	Capabilities []MultiMapping `json:"capabilities" yaml:"capabilities"`

	ExternalMappings []MultiMapping `json:"external-mappings,omitempty" yaml:"external-mappings,omitempty"`
}

type Capability struct {
	Id string `json:"id" yaml:"id"`

	Title string `json:"title" yaml:"title"`

	Description string `json:"description" yaml:"description"`
}

// Email represents a validated email address pattern
type Email string

// Datetime represents an ISO 8601 formatted datetime string
type Datetime string

// EvaluationLog contains the results of evaluating a set of Layer 2 controls.
type EvaluationLog struct {
	Evaluations []*ControlEvaluation `json:"evaluations" yaml:"evaluations"`

	Metadata Metadata `json:"metadata,omitempty" yaml:"metadata,omitempty"`
}

// ControlEvaluation contains the results of evaluating a single Layer 4 control.
type ControlEvaluation struct {
	Name string `json:"name" yaml:"name"`

	Result Result `json:"result" yaml:"result"`

	Message string `json:"message" yaml:"message"`

	Control SingleMapping `json:"control" yaml:"control"`

	// Enforce that control reference and the assessments' references match
	// This formulation uses the control's reference if the assessment doesn't include a reference
	AssessmentLogs []*AssessmentLog `json:"assessment-logs" yaml:"assessment-logs"`
}

// SingleMapping represents how a specific entry (control/requirement/procedure) maps to a MappingReference.
type SingleMapping struct {
	// ReferenceId should reference the corresponding MappingReference id from metadata
	ReferenceId string `json:"reference-id,omitempty" yaml:"reference-id,omitempty"`

	EntryId string `json:"entry-id" yaml:"entry-id"`

	Remarks string `json:"remarks,omitempty" yaml:"remarks,omitempty"`
}

// AssessmentLog contains the results of executing a single assessment procedure for a control requirement.
type AssessmentLog struct {
	// Requirement should map to the assessment requirement for this assessment.
	Requirement SingleMapping `json:"requirement" yaml:"requirement"`

	// Plan maps to the policy assessment plan being executed.
	Plan *SingleMapping `json:"plan,omitempty" yaml:"plan,omitempty"`

	// Description provides a summary of the assessment procedure.
	Description string `json:"description" yaml:"description"`

	// Result is the overall outcome of the assessment procedure, matching the result of the last step that was run.
	Result Result `json:"result" yaml:"result"`

	// Message provides additional context about the assessment result.
	Message string `json:"message" yaml:"message"`

	// Applicability is elevated from the Layer 2 Assessment Requirement to aid in execution and reporting.
	Applicability []string `json:"applicability" yaml:"applicability"`

	// Steps are sequential actions taken as part of the assessment, which may halt the assessment if a failure occurs.
	Steps []AssessmentStep `json:"steps" yaml:"steps"`

	// Steps-executed is the number of steps that were executed as part of the assessment.
	StepsExecuted int64 `json:"steps-executed,omitempty" yaml:"steps-executed,omitempty"`

	// Start is the timestamp when the assessment began.
	Start Datetime `json:"start" yaml:"start"`

	// End is the timestamp when the assessment concluded.
	End Datetime `json:"end,omitempty" yaml:"end,omitempty"`

	// Recommendation provides guidance on how to address a failed assessment.
	Recommendation string `json:"recommendation,omitempty" yaml:"recommendation,omitempty"`

	// ConfidenceLevel indicates the evaluator's confidence level in this specific assessment result.
	ConfidenceLevel ConfidenceLevel `json:"confidence-level,omitempty" yaml:"confidence-level,omitempty"`
}

type GuidanceDocument struct {
	Title string `json:"title" yaml:"title"`

	Metadata Metadata `json:"metadata" yaml:"metadata"`

	DocumentType DocumentType `json:"document-type" yaml:"document-type"`

	// Introductory text for the document to be used during rendering
	FrontMatter string `json:"front-matter,omitempty" yaml:"front-matter,omitempty"`

	Families []Family `json:"families,omitempty" yaml:"families,omitempty"`

	Guidelines []Guideline `json:"guidelines,omitempty" yaml:"guidelines,omitempty"`

	Exemptions []Exemption `json:"exemptions,omitempty" yaml:"exemptions,omitempty"`
}

type DocumentType string

// Guideline represents a single guideline within a guidance document
type Guideline struct {
	Id string `json:"id" yaml:"id"`

	Title string `json:"title" yaml:"title"`

	Objective string `json:"objective,omitempty" yaml:"objective,omitempty"`

	// Family id that this guideline belongs to
	Family string `json:"family" yaml:"family"`

	// Maps to fields commonly seen in controls with implementation guidance
	Recommendations []string `json:"recommendations,omitempty" yaml:"recommendations,omitempty"`

	// Extends allows you to add supplemental guidance within a local guidance document
	// like a control enhancement or from an imported guidance document.
	Extends *SingleMapping `json:"extends,omitempty" yaml:"extends,omitempty"`

	// Applicability specifies the contexts in which this guideline applies.
	Applicability []string `json:"applicability,omitempty" yaml:"applicability,omitempty"`

	Rationale *Rationale `json:"rationale,omitempty" yaml:"rationale,omitempty"`

	Statements []Statement `json:"statements,omitempty" yaml:"statements,omitempty"`

	GuidelineMappings []MultiMapping `json:"guideline-mappings,omitempty" yaml:"guideline-mappings,omitempty"`

	// A list for associated key principle ids
	PrincipleMappings []MultiMapping `json:"principle-mappings,omitempty" yaml:"principle-mappings,omitempty"`

	// SeeAlso lists related guideline IDs within the same Guidance document.
	SeeAlso []string `json:"see-also,omitempty" yaml:"see-also,omitempty"`
}

// Rationale provides contextual information to help with development and understanding of
// guideline intent.
type Rationale struct {
	Importance string `json:"importance" yaml:"importance"`

	Goals []string `json:"goals" yaml:"goals"`
}

// Statement represents a structural sub-requirement within a guideline
// They do not increase strictness and all statements within a guideline apply together.
type Statement struct {
	Id string `json:"id" yaml:"id"`

	Title string `json:"title,omitempty" yaml:"title,omitempty"`

	Text string `json:"text" yaml:"text"`

	Recommendations []string `json:"recommendations,omitempty" yaml:"recommendations,omitempty"`
}

// Exemption represents those who are exempt from the full guidance document.
type Exemption struct {
	// Description identifies who or what is exempt from the full guidance
	Description string `json:"description" yaml:"description"`

	// Reason explains why the exemption is granted
	Reason string `json:"reason" yaml:"reason"`

	// Redirect points to alternative guidelines or controls that should be followed instead
	Redirect *MultiMapping `json:"redirect,omitempty" yaml:"redirect,omitempty"`
}

// Policy represents a policy document with metadata, contacts, scope, imports, implementation plan, risks, and adherence requirements.
type Policy struct {
	Title string `json:"title" yaml:"title"`

	Metadata Metadata `json:"metadata" yaml:"metadata"`

	Contacts Contacts `json:"contacts" yaml:"contacts"`

	Scope Scope `json:"scope" yaml:"scope"`

	Imports Imports `json:"imports" yaml:"imports"`

	ImplementationPlan ImplementationPlan `json:"implementation-plan,omitempty" yaml:"implementation-plan,omitempty"`

	Risks Risks `json:"risks,omitempty" yaml:"risks,omitempty"`

	Adherence Adherence `json:"adherence" yaml:"adherence"`
}

// Contacts defines RACI roles for policy compliance and notification.
type Contacts struct {
	// responsible is the person or group responsible for implementing controls for technical requirements
	Responsible []Contact `json:"responsible" yaml:"responsible"`

	// accountable is the person or group accountable for evaluating and enforcing the efficacy of technical controls
	Accountable []Contact `json:"accountable" yaml:"accountable"`

	// consulted is an optional person or group who may be consulted for more information about the technical requirements
	Consulted []Contact `json:"consulted,omitempty" yaml:"consulted,omitempty"`

	// informed is an optional person or group who must receive updates about compliance with this policy
	Informed []Contact `json:"informed,omitempty" yaml:"informed,omitempty"`
}

// Scope defines what is included and excluded from policy applicability.
type Scope struct {
	In Dimensions `json:"in" yaml:"in"`

	Out Dimensions `json:"out,omitempty" yaml:"out,omitempty"`
}

// Dimensions specify the applicability criteria for a policy
type Dimensions struct {
	// technologies is an optional list of technology categories or services
	Technologies []string `json:"technologies,omitempty" yaml:"technologies,omitempty"`

	// geopolitical is an optional list of geopolitical regions
	Geopolitical []string `json:"geopolitical,omitempty" yaml:"geopolitical,omitempty"`

	// sensitivity is an optional list of data classification levels
	Sensitivity []string `json:"sensitivity,omitempty" yaml:"sensitivity,omitempty"`

	// users is an optional list of user roles
	Users []string `json:"users,omitempty" yaml:"users,omitempty"`

	Groups []string `json:"groups,omitempty" yaml:"groups,omitempty"`
}

// Imports defines external policies, controls, and guidelines required by this policy.
type Imports struct {
	Policies []string `json:"policies,omitempty" yaml:"policies,omitempty"`

	Catalogs []CatalogImport `json:"catalogs,omitempty" yaml:"catalogs,omitempty"`

	Guidance []GuidanceImport `json:"guidance,omitempty" yaml:"guidance,omitempty"`
}

// CatalogImport defines how to import control catalogs with optional exclusions, constraints, and assessment requirement modifications.
type CatalogImport struct {
	ReferenceId string `json:"reference-id" yaml:"reference-id"`

	Exclusions []string `json:"exclusions,omitempty" yaml:"exclusions,omitempty"`

	Constraints []Constraint `json:"constraints,omitempty" yaml:"constraints,omitempty"`

	AssessmentRequirementModifications []AssessmentRequirementModifier `json:"assessment-requirement-modifications,omitempty" yaml:"assessment-requirement-modifications,omitempty"`
}

// Constraint defines a prescriptive requirement that applies to a specific guidance or control.
type Constraint struct {
	// Unique ID for this constraint to enable Layer 4/5 tracking
	Id string `json:"id" yaml:"id"`

	// Links to the specific Guidance or Control being constrained
	TargetId string `json:"target-id" yaml:"target-id"`

	// The prescriptive requirement/constraint text
	Text string `json:"text" yaml:"text"`
}

// AssessmentRequirementModifier allows organizations to customize assessment requirements based on how an organization wants to gather evidence for the objective.
type AssessmentRequirementModifier struct {
	Id string `json:"id" yaml:"id"`

	TargetId string `json:"target-id" yaml:"target-id"`

	ModificationType ModType `json:"modification-type" yaml:"modification-type"`

	ModificationRationale string `json:"modification-rationale" yaml:"modification-rationale"`

	// The updated text of the assessment requirement
	Text string `json:"text,omitempty" yaml:"text,omitempty"`

	// The updated applicability of the assessment requirement
	Applicability []string `json:"applicability,omitempty" yaml:"applicability,omitempty"`

	// The updated recommendation for the assessment requirement
	Recommendation string `json:"recommendation,omitempty" yaml:"recommendation,omitempty"`
}

// ModType defines the type of modification to the assessment requirement.
type ModType string

// GuidanceImport defines how to import guidance documents with optional exclusions and constraints.
type GuidanceImport struct {
	ReferenceId string `json:"reference-id" yaml:"reference-id"`

	Exclusions []string `json:"exclusions,omitempty" yaml:"exclusions,omitempty"`

	// Constraints allow policy authors to define ad hoc minimum requirements (e.g., "review at least annually").
	Constraints []Constraint `json:"constraints,omitempty" yaml:"constraints,omitempty"`
}

// ImplementationPlan defines when and how the policy becomes active.
type ImplementationPlan struct {
	NotificationProcess string `json:"notification-process,omitempty" yaml:"notification-process,omitempty"`

	EvaluationTimeline ImplementationDetails `json:"evaluation-timeline" yaml:"evaluation-timeline"`

	EnforcementTimeline ImplementationDetails `json:"enforcement-timeline" yaml:"enforcement-timeline"`
}

// ImplementationDetails specifies the timeline for policy implementation.
type ImplementationDetails struct {
	Start Datetime `json:"start" yaml:"start"`

	End Datetime `json:"end,omitempty" yaml:"end,omitempty"`

	Notes string `json:"notes" yaml:"notes"`
}

// Risks defines mitigated and accepted risks addressed by this policy.
type Risks struct {
	// Mitigated risks only need reference-id and risk-id (no justification required)
	Mitigated []MultiMapping `json:"mitigated,omitempty" yaml:"mitigated,omitempty"`

	// Accepted risks require rationale (justification) and may include scope. Controls addressing these risks are implicitly identified through threat mappings.
	Accepted []AcceptedRisk `json:"accepted,omitempty" yaml:"accepted,omitempty"`
}

// RiskMapping maps a risk to a reference and optionally includes scope and justification.
type AcceptedRisk struct {
	Risk SingleMapping `json:"risk" yaml:"risk"`

	// Scope and justification are only required for accepted risks (e.g., risk is accepted for TLP:Green and TLP:Clear because they contain non-sensitive data)
	Scope Scope `json:"scope,omitempty" yaml:"scope,omitempty"`

	Justification string `json:"justification,omitempty" yaml:"justification,omitempty"`
}

// Adherence defines evaluation methods, assessment plans, enforcement methods, and non-compliance notifications.
type Adherence struct {
	EvaluationMethods []AcceptedMethod `json:"evaluation-methods,omitempty" yaml:"evaluation-methods,omitempty"`

	AssessmentPlans []AssessmentPlan `json:"assessment-plans,omitempty" yaml:"assessment-plans,omitempty"`

	EnforcementMethods []AcceptedMethod `json:"enforcement-methods,omitempty" yaml:"enforcement-methods,omitempty"`

	NonCompliance string `json:"non-compliance,omitempty" yaml:"non-compliance,omitempty"`
}

// AcceptedMethod defines a method for evaluation or enforcement.
type AcceptedMethod struct {
	Type string `json:"type" yaml:"type"`

	Description string `json:"description,omitempty" yaml:"description,omitempty"`

	Executor Actor `json:"executor,omitempty" yaml:"executor,omitempty"`
}

// AssessmentPlan defines how a specific assessment requirement is evaluated.
type AssessmentPlan struct {
	Id string `json:"id" yaml:"id"`

	RequirementId string `json:"requirement-id" yaml:"requirement-id"`

	Frequency string `json:"frequency" yaml:"frequency"`

	EvaluationMethods []AcceptedMethod `json:"evaluation-methods" yaml:"evaluation-methods"`

	EvidenceRequirements string `json:"evidence-requirements,omitempty" yaml:"evidence-requirements,omitempty"`

	Parameters []Parameter `json:"parameters,omitempty" yaml:"parameters,omitempty"`
}

// Parameter defines a configurable parameter for assessment or enforcement activities.
type Parameter struct {
	Id string `json:"id" yaml:"id"`

	Label string `json:"label" yaml:"label"`

	Description string `json:"description" yaml:"description"`

	AcceptedValues []string `json:"accepted-values,omitempty" yaml:"accepted-values,omitempty"`
}

type MethodType string
